### ISSUE TITLE
Positioning doesn't work properly

### ISSUE THREAD

**Issue by meevraxaw** [NolanKingdon/MMM-DailyPokemon#2]
Sadly, the module doesn't get positioned as configured. When the position is set to "top_right" or "bottom_right" the module stays in the middle of the right side. It's the same for the left side. When set to "middle_center" or e.g. "bottom_bar" it will stay in the middle of the left side. It's also covers other modules. I'd be very happy if you could fix it because I'd really like to use it. If you don't mind, being able to configure the size of the picture and the header would be nice, too.

Thank you in advance!

**Comment by Tomadelostacos** [comment]
By the size of the header, you mean the size the the font "Charmander - #4" ?

**Comment by Tomadelostacos** [comment]
Did a little fork for my own mirror, and i'll check out for the font size modification asap, it's not a huge load of work, so if you want : https://github.com/Tomadelostacos/MMM-DailyPokemon

**Comment by meevraxaw** [comment]
Thank you! I will try it out.

**Comment by NolanKingdon** [comment]
Just checking in - Did Tomadelostacos' fix work?

**Comment by Tomadelostacos** [comment]
I didn't fix the positionning, but i'll maybe have a look on font size modification tomorrow

**Comment by Tomadelostacos** [comment]
Font-size modification, done !

**Comment by NolanKingdon** [comment]
I'm going to be taking a look at the positioning issues tonight. I have an idea or two as to what may be causing the issues.

**Comment by NolanKingdon** [comment]
I couldn't replicate the overlap issue, but I did fix the issue where the module would stick the the left hand side when using "middle_center" or "bottom_bar".

I also added the pokemon name/number header to be effected by gbamode, because I love the look of that font.

**Comment by Tomadelostacos** [comment]
Nice job, didn't try the gba font for the name, gonna check it asap
