### ISSUE TITLE
module don´t show up

### ISSUE THREAD

**Issue by wuast94** [NolanKingdon/MMM-DailyPokemon#6]
this i what i added to my config: 

```
    {
      module: "MMM-DailyPokemon",
      position: "bottom_right",
      config: {
        updateInterval: 600000,
        minPoke: 1,
        maxPoke: 802,
        grayscale: true,
        showType: true,
        language: "de",
        stats: true,
        genera: true,
        gbaMode: true,
        nameSize: 26
      }
    },
```

But the module dont show up even if i switch the position, i cloned the repo and run npm install in the dir and all run´s without errors

**Comment by mcattle** [comment]
I'm having the same problem, and here's my config:

        {
            module: "MMM-DailyPokemon",
            position: "bottom_right",
            // disabled: true,
            config: {
                updateInterval: 600000,
                minPoke: 4,
                maxPoke: 802,
                grayscale: false,
                showType: true,
                language: "en",
                genera: true, 
                gbaMode: false,            
                nameSize: 26            
            }
        },

**Comment by mcattle** [comment]
I found the cause of the issue:

If you're using mmpm to install the module, it installs it under "Daily Pokemon" and not the expected MMM-DailyPokemon directory.  Installing this module manually fixes it.
