### ISSUE TITLE
After MM update 2.13 Daily Pokemon does not work

### ISSUE THREAD

**Issue by losipher** [NolanKingdon/MMM-DailyPokemon#9]
As the title states. After updating magic mirror to 2.13 the daily pokemon module does not work. I have tried changing the required version code to 2.13 but that did not seem to change anything.

**Comment by wuast94** [comment]
same here .. was wondering why my mirror goes black ... since the last release is over a year ago i dont have much hope for fixing ..

**Comment by losipher** [comment]
If I get really board I will take a look at it see if I can fork it and fix.

**Comment by AndyHazz** [comment]
It's the comment lines in the /translations/en.json and fr.json files - not valid json and MM 2.13 is probably being stricter.
Remove those comment lines and it works.

**Comment by AndyHazz** [comment]
PR #10 will sort that out if it can be merged in

**Comment by NolanKingdon** [comment]
Didn't see this until now. Merged #10 - Should be fixed.
